require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EventActivitiesController do

  # This should return the minimal set of attributes required to create a valid
  # EventActivity. As you add validations to EventActivity, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EventActivitiesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all event_activities as @event_activities" do
      event_activity = EventActivity.create! valid_attributes
      get :index, {}, valid_session
      assigns(:event_activities).should eq([event_activity])
    end
  end

  describe "GET show" do
    it "assigns the requested event_activity as @event_activity" do
      event_activity = EventActivity.create! valid_attributes
      get :show, {:id => event_activity.to_param}, valid_session
      assigns(:event_activity).should eq(event_activity)
    end
  end

  describe "GET new" do
    it "assigns a new event_activity as @event_activity" do
      get :new, {}, valid_session
      assigns(:event_activity).should be_a_new(EventActivity)
    end
  end

  describe "GET edit" do
    it "assigns the requested event_activity as @event_activity" do
      event_activity = EventActivity.create! valid_attributes
      get :edit, {:id => event_activity.to_param}, valid_session
      assigns(:event_activity).should eq(event_activity)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new EventActivity" do
        expect {
          post :create, {:event_activity => valid_attributes}, valid_session
        }.to change(EventActivity, :count).by(1)
      end

      it "assigns a newly created event_activity as @event_activity" do
        post :create, {:event_activity => valid_attributes}, valid_session
        assigns(:event_activity).should be_a(EventActivity)
        assigns(:event_activity).should be_persisted
      end

      it "redirects to the created event_activity" do
        post :create, {:event_activity => valid_attributes}, valid_session
        response.should redirect_to(EventActivity.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved event_activity as @event_activity" do
        # Trigger the behavior that occurs when invalid params are submitted
        EventActivity.any_instance.stub(:save).and_return(false)
        post :create, {:event_activity => {}}, valid_session
        assigns(:event_activity).should be_a_new(EventActivity)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        EventActivity.any_instance.stub(:save).and_return(false)
        post :create, {:event_activity => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested event_activity" do
        event_activity = EventActivity.create! valid_attributes
        # Assuming there are no other event_activities in the database, this
        # specifies that the EventActivity created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        EventActivity.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => event_activity.to_param, :event_activity => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested event_activity as @event_activity" do
        event_activity = EventActivity.create! valid_attributes
        put :update, {:id => event_activity.to_param, :event_activity => valid_attributes}, valid_session
        assigns(:event_activity).should eq(event_activity)
      end

      it "redirects to the event_activity" do
        event_activity = EventActivity.create! valid_attributes
        put :update, {:id => event_activity.to_param, :event_activity => valid_attributes}, valid_session
        response.should redirect_to(event_activity)
      end
    end

    describe "with invalid params" do
      it "assigns the event_activity as @event_activity" do
        event_activity = EventActivity.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EventActivity.any_instance.stub(:save).and_return(false)
        put :update, {:id => event_activity.to_param, :event_activity => {}}, valid_session
        assigns(:event_activity).should eq(event_activity)
      end

      it "re-renders the 'edit' template" do
        event_activity = EventActivity.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EventActivity.any_instance.stub(:save).and_return(false)
        put :update, {:id => event_activity.to_param, :event_activity => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested event_activity" do
      event_activity = EventActivity.create! valid_attributes
      expect {
        delete :destroy, {:id => event_activity.to_param}, valid_session
      }.to change(EventActivity, :count).by(-1)
    end

    it "redirects to the event_activities list" do
      event_activity = EventActivity.create! valid_attributes
      delete :destroy, {:id => event_activity.to_param}, valid_session
      response.should redirect_to(event_activities_url)
    end
  end

end
